version: 2.1

jobs: 
    build:
        docker: 
            - image: cimg/node:19.8
        working_directory: ~/app
        environment:
            MY_VAR: "tienhuynh-tn"
        steps:
            - checkout
            - run:
                name: "Echo environment Variable"
                command: echo $MY_VAR
            - run: 
                name: "Check Node version"
                command: node --version
            - run: 
                name: "Install NPM Packages"
                command: npm install
