# .circleci/config.yml file 
version: 2.1

jobs:
   build:
       docker: 
           - image: cimg/mode:19/8.1
       working_directory: ~/app
       environment:
           MY_VAR: "tienhuynh-tn"
       steps:
           - run: echo $MY_VAR
           - run: node --version
           - run: npm install