version: 2.1

jobs: 
    build:
        docker: 
            - image: cimg/node:19.1.8
        working_directory: ~/app
        environment:
            MY_VAR: "tienhuynh-tn"
        steps:
            - run:
                name: "Echo environment Variable"
                command: echo $MY_VAR